// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OhMyPc.Infrastructure.Persistence;

#nullable disable

namespace OhMyPc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808132725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.CredentialEntity", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.DailyUsageEntity", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CostMicroUsd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date", "DeviceId", "Client", "Provider", "Model");

                    b.HasIndex("Date", "Client");

                    b.ToTable("DailyUsage", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.DataSourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DataSources", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.NotificationRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespectQuietHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<int>("TriggerKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationRules", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.NotificationStateEntity", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastMatched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastNotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastNumericValue")
                        .HasColumnType("REAL");

                    b.Property<string>("LastTextValue")
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId", "SubjectKey");

                    b.ToTable("NotificationStates", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.QuotaCurrentEntity", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Limit")
                        .HasColumnType("REAL");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Remaining")
                        .HasColumnType("REAL");

                    b.Property<string>("ResetAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Used")
                        .HasColumnType("REAL");

                    b.HasKey("SourceId", "WindowKey");

                    b.ToTable("CurrentQuotas", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.CredentialEntity", b =>
                {
                    b.HasOne("OhMyPc.Infrastructure.Persistence.DataSourceEntity", "Source")
                        .WithOne("Credential")
                        .HasForeignKey("OhMyPc.Infrastructure.Persistence.CredentialEntity", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.QuotaCurrentEntity", b =>
                {
                    b.HasOne("OhMyPc.Infrastructure.Persistence.DataSourceEntity", "Source")
                        .WithMany("Quotas")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.DataSourceEntity", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("Quotas");
                });
#pragma warning restore 612, 618
        }
    }
}
