// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OhMyPc.Infrastructure.Persistence;

#nullable disable

namespace OhMyPc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.CredentialEntity", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.DailyUsageEntity", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CostMicroUsd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date", "DeviceId", "Client", "Provider", "Model");

                    b.HasIndex("Date", "Client");

                    b.ToTable("DailyUsage", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.DataSourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelStatusUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DataSources", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.AutomationRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RespectQuietHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "EventType");

                    b.ToTable("AutomationRules", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.AutomationRuleStateEntity", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastExecutedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId", "SubjectKey");

                    b.ToTable("AutomationRuleStates", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.AutomationSourceStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AutomationSourceStates", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending();

                    b.HasIndex("Severity", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("Source", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.QuotaCurrentEntity", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Limit")
                        .HasColumnType("REAL");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProgressLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("Remaining")
                        .HasColumnType("REAL");

                    b.Property<string>("ResetAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Used")
                        .HasColumnType("REAL");

                    b.HasKey("SourceId", "WindowKey");

                    b.ToTable("CurrentQuotas", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.VpnAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedAuthData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResetDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransferLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VpnAccounts", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.VpnDailyUsageEntity", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransferLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("VpnDailyUsage", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.CredentialEntity", b =>
                {
                    b.HasOne("OhMyPc.Infrastructure.Persistence.DataSourceEntity", "Source")
                        .WithOne("Credential")
                        .HasForeignKey("OhMyPc.Infrastructure.Persistence.CredentialEntity", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.AutomationRuleStateEntity", b =>
                {
                    b.HasOne("OhMyPc.Infrastructure.Persistence.AutomationRuleEntity", "Rule")
                        .WithMany("States")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.QuotaCurrentEntity", b =>
                {
                    b.HasOne("OhMyPc.Infrastructure.Persistence.DataSourceEntity", "Source")
                        .WithMany("Quotas")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.DataSourceEntity", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("OhMyPc.Infrastructure.Persistence.AutomationRuleEntity", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
